def save_user_settings(gui):
    s = gui.settings
    s.setValue("output_mode", gui.output_mode_combo.currentText())
    s.setValue("source_lang", gui.lang_whisper_combo.currentText())
    s.setValue("ai_polish", gui.enable_ai_polish_cb.isChecked())
    s.setValue("final_output_folder", gui.final_output_folder_edit.text())
    s.setValue("audio_folder", gui.audio_folder_edit.text())
    s.setValue("srt_output_folder", gui.srt_output_folder_edit.text())
    s.setValue("voice_output_folder", gui.voice_output_folder_edit.text())
    s.setValue("audio_source", gui.audio_source_edit.text())
    s.setValue("background_audio", gui.bg_music_edit.text())
    s.setValue("mixed_audio", gui.mixed_audio_edit.text())
    s.setValue("voice_name", gui.voice_name_combo.currentText())
    s.setValue("use_existing_audio", gui.use_existing_audio_radio.isChecked())
    s.setValue("keep_audio", gui.keep_audio_cb.isChecked())
    s.setValue("keep_timeline", gui.keep_timeline_cb.isChecked())
    s.setValue("auto_preview_frame", gui.auto_preview_frame_cb.isChecked())
    s.setValue("subtitle_font", gui.subtitle_font_combo.currentText())
    s.setValue("subtitle_size", gui.subtitle_font_size_spin.value())
    s.setValue("subtitle_align", gui.subtitle_align_combo.currentText())
    s.setValue("subtitle_x_offset", gui.subtitle_x_offset_spin.value())
    s.setValue("subtitle_vertical_offset", gui.subtitle_bottom_offset_spin.value())
    s.setValue("subtitle_color", gui.subtitle_color_hex)
    s.setValue("subtitle_background", gui.subtitle_background_cb.isChecked())
    s.setValue("voice_speed", gui.voice_speed_spin.currentText())
    s.setValue("voice_tone", gui.voice_tone_combo.currentText())
    s.setValue("voice_gain", gui.voice_gain_spin.value())
    s.setValue("bg_gain", gui.bg_gain_spin.value())
    s.setValue("advanced_open", gui.advanced_group.isChecked())


def load_user_settings(gui):
    s = gui.settings
    gui.output_mode_combo.setCurrentText(s.value("output_mode", gui.output_mode_combo.currentText()))
    source_lang = s.value("source_lang", gui.lang_whisper_combo.currentText())
    source_index = gui.lang_whisper_combo.findText(source_lang)
    if source_index < 0:
        source_index = gui.lang_whisper_combo.findData(source_lang)
    if source_index >= 0:
        gui.lang_whisper_combo.setCurrentIndex(source_index)
    gui.enable_ai_polish_cb.setChecked(str(s.value("ai_polish", gui.enable_ai_polish_cb.isChecked())).lower() == "true")
    gui.final_output_folder_edit.setText(s.value("final_output_folder", gui.final_output_folder_edit.text()))
    gui.audio_folder_edit.setText(s.value("audio_folder", gui.audio_folder_edit.text()))
    gui.srt_output_folder_edit.setText(s.value("srt_output_folder", gui.srt_output_folder_edit.text()))
    gui.voice_output_folder_edit.setText(s.value("voice_output_folder", gui.voice_output_folder_edit.text()))
    gui.audio_source_edit.setText(s.value("audio_source", gui.audio_source_edit.text()))
    gui.bg_music_edit.setText(s.value("background_audio", gui.bg_music_edit.text()))
    gui.mixed_audio_edit.setText(s.value("mixed_audio", gui.mixed_audio_edit.text()))
    gui.voice_name_combo.setCurrentText(s.value("voice_name", gui.voice_name_combo.currentText()))
    gui.keep_audio_cb.setChecked(str(s.value("keep_audio", gui.keep_audio_cb.isChecked())).lower() == "true")
    gui.keep_timeline_cb.setChecked(str(s.value("keep_timeline", gui.keep_timeline_cb.isChecked())).lower() == "true")
    gui.auto_preview_frame_cb.setChecked(str(s.value("auto_preview_frame", gui.auto_preview_frame_cb.isChecked())).lower() == "true")
    gui.subtitle_font_combo.setCurrentText(s.value("subtitle_font", gui.subtitle_font_combo.currentText()))
    gui.subtitle_font_size_spin.setValue(int(s.value("subtitle_size", gui.subtitle_font_size_spin.value())))
    gui.subtitle_align_combo.setCurrentText(s.value("subtitle_align", gui.subtitle_align_combo.currentText()))
    gui.subtitle_x_offset_spin.setValue(int(s.value("subtitle_x_offset", gui.subtitle_x_offset_spin.value())))
    gui.subtitle_bottom_offset_spin.setValue(int(s.value("subtitle_vertical_offset", gui.subtitle_bottom_offset_spin.value())))
    gui.subtitle_color_hex = str(s.value("subtitle_color", gui.subtitle_color_hex)).upper()
    gui.subtitle_color_btn.setText(f"Color: {gui.subtitle_color_hex}")
    gui.subtitle_background_cb.setChecked(str(s.value("subtitle_background", gui.subtitle_background_cb.isChecked())).lower() == "true")
    gui.voice_speed_spin.setCurrentText(s.value("voice_speed", gui.voice_speed_spin.currentText()))
    gui.voice_tone_combo.setCurrentText(s.value("voice_tone", gui.voice_tone_combo.currentText()))
    gui.voice_gain_spin.setValue(float(s.value("voice_gain", gui.voice_gain_spin.value())))
    gui.bg_gain_spin.setValue(float(s.value("bg_gain", gui.bg_gain_spin.value())))
    use_existing = str(s.value("use_existing_audio", "false")).lower() == "true"
    gui.use_existing_audio_radio.setChecked(use_existing)
    gui.use_generated_audio_radio.setChecked(not use_existing)
    gui.advanced_group.setChecked(str(s.value("advanced_open", "false")).lower() == "true")
    gui.on_advanced_toggled(gui.advanced_group.isChecked())
    gui.on_audio_source_mode_changed()
    gui.update_subtitle_preview_style()
    gui.on_output_mode_changed(gui.output_mode_combo.currentText())
    gui.refresh_ui_state()
