import os

from PySide6.QtCore import QSize, Qt
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QFrame,
    QHBoxLayout,
    QLabel,
    QProgressBar,
    QPushButton,
    QScrollArea,
    QSizePolicy,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from runtime_paths import asset_path
from widgets import MpvVideoView, TimelineWidget, VideoView
from utils.icon_utils import load_icon
from utils.media_backend import is_mpv_backend_available


def _set_preview_icon_button(button: QPushButton, icon_path: str, tooltip: str):
    button.setText("")
    button.setFixedSize(38, 38)
    button.setIcon(load_icon(icon_path, 18))
    button.setIconSize(QSize(18, 18))
    button.setStyleSheet("QPushButton { padding: 0; }")


class TimelineTrackLabels(QFrame):
    def __init__(self, timeline, parent=None):
        super().__init__(parent)
        self._timeline = timeline
        self.setObjectName("timelineTrackLabels")
        self.setFixedWidth(112)
        self._rows = {}

        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        self.header = QLabel("Tracks")
        self.header.setFixedHeight(28)
        self.header.setAlignment(Qt.AlignVCenter | Qt.AlignLeft)
        self.header.setContentsMargins(14, 0, 0, 0)
        self.header.setObjectName("helperLabel")
        layout.addWidget(self.header)

        for key, title in (("subtitle", "Subtitle"), ("audio", "Audio"), ("video", "Video")):
            row = QFrame()
            row_layout = QVBoxLayout(row)
            row_layout.setContentsMargins(14, 8, 10, 8)
            row_layout.setSpacing(1)
            title_label = QLabel(title)
            title_label.setObjectName("statusHeadline")
            title_label.setStyleSheet("font-size: 12px; font-weight: 700;")
            row_layout.addStretch()
            row_layout.addWidget(title_label)
            row_layout.addStretch()
            layout.addWidget(row)
            self._rows[key] = row
        layout.addStretch()
        self.sync_to_timeline()

    def sync_to_timeline(self):
        for key, row in self._rows.items():
            visible = self._timeline.is_track_visible(key)
            row.setVisible(visible)
            layout = getattr(self._timeline, "_layout", {})
            row_height = int(layout.get(key, {}).get("h", 0)) if visible else 0
            row.setFixedHeight(row_height)


def _build_timeline_track_labels(timeline):
    return TimelineTrackLabels(timeline)


def build_preview_panel(gui):
    right_panel = QWidget()
    right_panel.setObjectName("rightPanel")
    right_layout = QVBoxLayout(right_panel)
    right_layout.setContentsMargins(0, 0, 0, 0)
    right_layout.setSpacing(10)

    gui.preview_context_label = QLabel("Choose a video to start previewing. Subtitle and voice status will appear here as you work.")
    gui.preview_context_label.setWordWrap(True)
    gui.preview_context_label.setObjectName("previewContextLabel")
    gui.preview_context_label.hide()
    gui.frame_preview_status_label = QLabel("Exact frame preview updates here when available.")
    gui.frame_preview_status_label.setWordWrap(True)
    gui.frame_preview_status_label.setObjectName("helperLabel")
    gui.frame_preview_status_label.hide()
    gui.frame_preview_image_label = QLabel("No frame preview yet")
    gui.frame_preview_image_label.setAlignment(Qt.AlignCenter)
    gui.frame_preview_image_label.setMinimumHeight(170)
    gui.frame_preview_image_label.hide()

    gui.video_view = MpvVideoView() if is_mpv_backend_available() else VideoView()
    gui.video_view.setMinimumHeight(320)
    gui.video_view.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    gui.timeline = TimelineWidget()
    gui.timeline.seekRequested.connect(gui.set_position)
    gui.timeline.segmentSelected.connect(gui.on_timeline_segment_selected)
    gui.timeline.segmentTimingEditStarted.connect(gui.on_timeline_segment_timing_edit_started)
    gui.timeline.segmentTimingChanged.connect(gui.on_timeline_segment_timing_changed)
    gui.timeline.zoomChanged.connect(lambda value: gui.timeline_zoom_label.setText(f"{value}%"))
    gui.time_label = QLabel("00:00 / 00:00")
    gui.time_label.setStyleSheet("font-weight: bold; min-width: 100px; color: #6ee7d6;")

    preview_card = QFrame()
    preview_card.setObjectName("statusCard")
    preview_card_layout = QVBoxLayout(preview_card)
    preview_card_layout.setContentsMargins(12, 12, 12, 10)
    preview_card_layout.setSpacing(8)
    preview_card_layout.addWidget(gui.preview_context_label)
    preview_card_layout.addWidget(gui.frame_preview_status_label)
    preview_card_layout.addWidget(gui.frame_preview_image_label)
    preview_card_layout.addWidget(gui.video_view, 1)

    timeline_card = QFrame()
    timeline_card.setObjectName("statusCard")
    timeline_layout = QVBoxLayout(timeline_card)
    timeline_layout.setContentsMargins(12, 10, 12, 10)
    timeline_layout.setSpacing(8)

    timeline_header_layout = QHBoxLayout()
    timeline_header_layout.setSpacing(10)
    timeline_copy_layout = QVBoxLayout()
    timeline_copy_layout.setSpacing(1)
    timeline_title = QLabel("Timeline")
    timeline_title.setObjectName("statusHeadline")
    timeline_meta = QLabel("Editor-first layout with dedicated video, audio, and subtitle lanes.")
    timeline_meta.setObjectName("helperLabel")
    timeline_copy_layout.addWidget(timeline_title)
    timeline_copy_layout.addWidget(timeline_meta)
    timeline_header_layout.addLayout(timeline_copy_layout, 1)
    gui.timeline_video_toggle_btn = QPushButton("Video")
    gui.timeline_video_toggle_btn.setCheckable(True)
    gui.timeline_video_toggle_btn.setChecked(True)
    gui.timeline_video_toggle_btn.setFixedWidth(62)
    gui.timeline_audio_toggle_btn = QPushButton("Audio")
    gui.timeline_audio_toggle_btn.setCheckable(True)
    gui.timeline_audio_toggle_btn.setChecked(True)
    gui.timeline_audio_toggle_btn.setFixedWidth(62)
    gui.timeline_subtitle_toggle_btn = QPushButton("Subtitle")
    gui.timeline_subtitle_toggle_btn.setCheckable(True)
    gui.timeline_subtitle_toggle_btn.setChecked(True)
    gui.timeline_subtitle_toggle_btn.setFixedWidth(72)
    for btn in (gui.timeline_video_toggle_btn, gui.timeline_audio_toggle_btn, gui.timeline_subtitle_toggle_btn):
        btn.setObjectName("workflowTabBtn")
    gui.timeline_video_toggle_btn.toggled.connect(lambda checked: gui.timeline.set_track_visibility("video", checked))
    gui.timeline_audio_toggle_btn.toggled.connect(lambda checked: gui.timeline.set_track_visibility("audio", checked))
    gui.timeline_subtitle_toggle_btn.toggled.connect(lambda checked: gui.timeline.set_track_visibility("subtitle", checked))
    timeline_header_layout.addWidget(gui.timeline_subtitle_toggle_btn)
    timeline_header_layout.addWidget(gui.timeline_audio_toggle_btn)
    timeline_header_layout.addWidget(gui.timeline_video_toggle_btn)
    gui.timeline_undo_btn = QPushButton("Undo")
    gui.timeline_undo_btn.setFixedWidth(58)
    gui.timeline_undo_btn.setEnabled(False)
    gui.timeline_redo_btn = QPushButton("Redo")
    gui.timeline_redo_btn.setFixedWidth(58)
    gui.timeline_redo_btn.setEnabled(False)
    gui.timeline_split_btn = QPushButton("Split")
    gui.timeline_split_btn.setFixedWidth(58)
    gui.timeline_split_btn.setEnabled(False)
    gui.timeline_delete_btn = QPushButton("Delete")
    gui.timeline_delete_btn.setFixedWidth(62)
    gui.timeline_delete_btn.setEnabled(False)
    gui.timeline_nudge_left_btn = QPushButton("<")
    gui.timeline_nudge_left_btn.setFixedWidth(34)
    gui.timeline_nudge_left_btn.setEnabled(False)
    gui.timeline_nudge_right_btn = QPushButton(">")
    gui.timeline_nudge_right_btn.setFixedWidth(34)
    gui.timeline_nudge_right_btn.setEnabled(False)
    gui.timeline_ripple_left_btn = QPushButton("<<")
    gui.timeline_ripple_left_btn.setFixedWidth(40)
    gui.timeline_ripple_left_btn.setEnabled(False)
    gui.timeline_ripple_right_btn = QPushButton(">>")
    gui.timeline_ripple_right_btn.setFixedWidth(40)
    gui.timeline_ripple_right_btn.setEnabled(False)
    gui.timeline_undo_btn.clicked.connect(gui.undo_last_timeline_timing_edit)
    gui.timeline_redo_btn.clicked.connect(gui.redo_last_timeline_timing_edit)
    gui.timeline_split_btn.clicked.connect(gui.split_selected_timeline_segment)
    gui.timeline_delete_btn.clicked.connect(gui.delete_selected_timeline_segment)
    gui.timeline_nudge_left_btn.clicked.connect(lambda: gui.nudge_selected_timeline_segment(-0.05))
    gui.timeline_nudge_right_btn.clicked.connect(lambda: gui.nudge_selected_timeline_segment(0.05))
    gui.timeline_ripple_left_btn.clicked.connect(lambda: gui.ripple_nudge_selected_timeline_segment(-0.05))
    gui.timeline_ripple_right_btn.clicked.connect(lambda: gui.ripple_nudge_selected_timeline_segment(0.05))
    timeline_header_layout.addWidget(gui.timeline_undo_btn)
    timeline_header_layout.addWidget(gui.timeline_redo_btn)
    timeline_header_layout.addWidget(gui.timeline_split_btn)
    timeline_header_layout.addWidget(gui.timeline_delete_btn)
    timeline_header_layout.addWidget(gui.timeline_nudge_left_btn)
    timeline_header_layout.addWidget(gui.timeline_nudge_right_btn)
    timeline_header_layout.addWidget(gui.timeline_ripple_left_btn)
    timeline_header_layout.addWidget(gui.timeline_ripple_right_btn)
    gui.timeline_zoom_out_btn = QPushButton("-")
    gui.timeline_zoom_out_btn.setFixedWidth(34)
    gui.timeline_zoom_label = QLabel(f"{gui.timeline.zoom_percent()}%")
    gui.timeline_zoom_label.setObjectName("helperLabel")
    gui.timeline_zoom_label.setAlignment(Qt.AlignCenter)
    gui.timeline_zoom_label.setMinimumWidth(48)
    gui.timeline_zoom_in_btn = QPushButton("+")
    gui.timeline_zoom_in_btn.setFixedWidth(34)
    gui.timeline_zoom_reset_btn = QPushButton("Fit")
    gui.timeline_zoom_reset_btn.setFixedWidth(52)
    gui.timeline_zoom_out_btn.clicked.connect(gui.timeline.zoom_out)
    gui.timeline_zoom_in_btn.clicked.connect(gui.timeline.zoom_in)
    gui.timeline_zoom_reset_btn.clicked.connect(gui.timeline.reset_zoom)
    timeline_header_layout.addWidget(gui.timeline_zoom_out_btn)
    timeline_header_layout.addWidget(gui.timeline_zoom_label)
    timeline_header_layout.addWidget(gui.timeline_zoom_in_btn)
    timeline_header_layout.addWidget(gui.timeline_zoom_reset_btn)
    timeline_header_layout.addWidget(gui.time_label)
    timeline_layout.addLayout(timeline_header_layout)

    timeline_body_layout = QHBoxLayout()
    timeline_body_layout.setSpacing(0)
    gui.timeline_track_labels = _build_timeline_track_labels(gui.timeline)
    gui.timeline.layoutChanged.connect(gui.timeline_track_labels.sync_to_timeline)
    timeline_body_layout.addWidget(gui.timeline_track_labels)
    timeline_body_layout.addWidget(gui.timeline, 1)
    timeline_layout.addLayout(timeline_body_layout)

    controls_layout = QHBoxLayout()
    controls_layout.setSpacing(10)
    icons_dir = asset_path("icons")
    gui.play_btn = QPushButton()
    gui.stop_btn = QPushButton()
    gui.preview_btn = QPushButton()
    gui.reset_framing_btn = QPushButton("Reset Framing")
    gui.blur_area_btn = QPushButton()
    gui.blur_area_btn.setCheckable(True)
    _set_preview_icon_button(gui.play_btn, os.path.join(icons_dir, "play.svg"), "Play or pause preview")
    _set_preview_icon_button(gui.stop_btn, os.path.join(icons_dir, "reset.svg"), "Reset preview to the beginning")
    _set_preview_icon_button(gui.preview_btn, os.path.join(icons_dir, "preview.svg"), "Render a fresh preview using current subtitle and audio")
    _set_preview_icon_button(gui.blur_area_btn, os.path.join(icons_dir, "blur.svg"), "Toggle blur area editing")
    controls_layout.addWidget(gui.play_btn)
    controls_layout.addWidget(gui.stop_btn)
    controls_layout.addWidget(gui.preview_btn)
    controls_layout.addWidget(gui.reset_framing_btn)
    controls_layout.addWidget(gui.blur_area_btn)

    preview_audio_layout = QHBoxLayout()
    preview_audio_layout.setSpacing(10)
    gui.preview_volume_down_btn = QPushButton()
    gui.preview_mute_btn = QPushButton()
    gui.preview_volume_up_btn = QPushButton()
    _set_preview_icon_button(gui.preview_volume_down_btn, os.path.join(icons_dir, "volume_down.svg"), "Lower preview volume")
    _set_preview_icon_button(gui.preview_mute_btn, os.path.join(icons_dir, "volume_mute.svg"), "Mute preview")
    _set_preview_icon_button(gui.preview_volume_up_btn, os.path.join(icons_dir, "volume_up.svg"), "Raise preview volume")
    gui.preview_volume_label = QLabel("100%")
    gui.preview_volume_label.setObjectName("helperLabel")
    gui.preview_speed_combo = QComboBox()
    gui.preview_speed_combo.addItem("0.75x", 0.75)
    gui.preview_speed_combo.addItem("1.0x", 1.0)
    gui.preview_speed_combo.addItem("1.25x", 1.25)
    gui.preview_speed_combo.addItem("1.5x", 1.5)
    gui.preview_speed_combo.addItem("2.0x", 2.0)
    gui.preview_speed_combo.setCurrentIndex(1)
    preview_audio_layout.addWidget(gui.preview_volume_down_btn)
    preview_audio_layout.addWidget(gui.preview_mute_btn)
    preview_audio_layout.addWidget(gui.preview_volume_up_btn)
    preview_audio_layout.addWidget(gui.preview_volume_label)
    preview_audio_layout.addStretch(1)
    preview_audio_layout.addWidget(QLabel("Speed"))
    preview_audio_layout.addWidget(gui.preview_speed_combo)

    controls_bar = QFrame()
    controls_bar.setObjectName("timelineControlsBar")
    controls_bar_layout = QHBoxLayout(controls_bar)
    controls_bar_layout.setContentsMargins(12, 10, 12, 10)
    controls_bar_layout.setSpacing(18)
    controls_bar_layout.addLayout(controls_layout)
    controls_bar_layout.addLayout(preview_audio_layout, 1)

    gui.progress_bar = QProgressBar()
    gui.progress_bar.setFixedHeight(8)
    gui.progress_bar.setTextVisible(False)
    timeline_layout.addWidget(gui.progress_bar)

    gui.translated_text = QTextEdit()
    gui.translated_text.setPlaceholderText("Vietnamese subtitle text will appear here. You can edit it before export.")
    gui.translated_text.hide()
    gui.transcript_text = QTextEdit()
    gui.transcript_text.setPlaceholderText("The original subtitle transcript will appear here...")
    gui.transcript_text.hide()

    inspector_card = QFrame()
    inspector_card.setObjectName("statusCard")
    inspector_card.setMinimumWidth(320)
    inspector_card.setMaximumWidth(380)
    inspector_layout = QVBoxLayout(inspector_card)
    inspector_layout.setContentsMargins(14, 14, 14, 14)
    inspector_layout.setSpacing(10)

    inspector_header = QHBoxLayout()
    inspector_header.setSpacing(8)
    inspector_copy = QVBoxLayout()
    inspector_copy.setSpacing(2)
    inspector_title = QLabel("Subtitle Inspector")
    inspector_title.setObjectName("statusHeadline")
    inspector_copy.addWidget(inspector_title)
    inspector_header.addLayout(inspector_copy, 1)
    inspector_layout.addLayout(inspector_header)

    inspector_actions_row = QHBoxLayout()
    inspector_actions_row.setSpacing(8)
    gui.rewrite_translation_btn = QPushButton("Rewrite")
    gui.rewrite_selected_segment_btn = QPushButton("Rewrite Selected Subtitle")
    gui.import_translation_btn = QPushButton("Import SRT")
    gui.rewrite_selected_segment_btn.clicked.connect(gui.run_rewrite_selected_segment)
    inspector_actions_row.addWidget(gui.rewrite_translation_btn)
    inspector_actions_row.addWidget(gui.rewrite_selected_segment_btn)
    inspector_actions_row.addWidget(gui.import_translation_btn)
    inspector_layout.addLayout(inspector_actions_row)

    gui.show_original_subtitle_cb = QCheckBox("Show original")
    gui.show_original_subtitle_cb.setChecked(True)
    inspector_toggle_row = QHBoxLayout()
    inspector_toggle_row.setSpacing(10)
    inspector_toggle_row.addWidget(gui.show_original_subtitle_cb)
    inspector_toggle_row.addStretch(1)
    inspector_layout.addLayout(inspector_toggle_row)

    inspector_nav_row = QHBoxLayout()
    inspector_nav_row.setSpacing(8)
    gui.segment_prev_btn = QPushButton("Prev")
    gui.segment_prev_btn.clicked.connect(lambda: gui.step_selected_segment(-1))
    gui.segment_next_btn = QPushButton("Next")
    gui.segment_next_btn.clicked.connect(lambda: gui.step_selected_segment(1))
    gui.segment_selection_label = QLabel("No subtitle selected")
    gui.segment_selection_label.setObjectName("helperLabel")
    inspector_nav_row.addWidget(gui.segment_prev_btn)
    inspector_nav_row.addWidget(gui.segment_next_btn)
    inspector_nav_row.addWidget(gui.segment_selection_label, 1)
    inspector_layout.addLayout(inspector_nav_row)

    gui.segment_editor_scroll = QScrollArea()
    gui.segment_editor_scroll.setObjectName("segmentEditorScroll")
    gui.segment_editor_scroll.setWidgetResizable(True)
    gui.segment_editor_scroll.setFrameShape(QFrame.NoFrame)
    gui.segment_editor_container = QWidget()
    gui.segment_editor_container.setObjectName("segmentEditorContainer")
    gui.segment_editor_layout = QVBoxLayout(gui.segment_editor_container)
    gui.segment_editor_layout.setContentsMargins(0, 0, 0, 0)
    gui.segment_editor_layout.setSpacing(10)
    gui.segment_editor_scroll.setWidget(gui.segment_editor_container)
    inspector_layout.addWidget(gui.segment_editor_scroll, 1)

    workspace_row = QHBoxLayout()
    workspace_row.setSpacing(10)
    workspace_row.addWidget(preview_card, 1)
    workspace_row.addWidget(inspector_card, 0)

    right_layout.addLayout(workspace_row, 5)
    right_layout.addWidget(controls_bar, 0)
    right_layout.addWidget(timeline_card, 0)
    return right_panel


